_target_: src.models.vae.VAE

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

latent_dim: 8
kl_weight: 1e-3

img_size: 28


# compile model for faster training with pytorch 2.0
compile: false
